// USING LOCALHOST
### Display all contacts
GET http://localhost:3000/contacts

### Find a contact by ID
GET http://localhost:3000/contacts/634c3b91ec2716f690e4340b

### Add new contact to address book
POST http://localhost:3000/contacts
Content-Type: application/json

{
  "firstName": "Dominic",
  "lastname": "Caravaggio",
  "streetAddress": "922 Main SW",
  "city": "Cardston",
  "state": "Alberta",
  "zipCode": "T0K 0K0",
  "country": "Canada"
}

### Update an existing contact in address book
PUT http://localhost:3000/contacts/6350c6e5100b909afa5a5bf2
Content-Type: application/json

{
  "firstName": "Dominic",
  "lastName": "Caravaggio",
  "streetAddress": "123 His Street",
  "city": "Cardston",
  "state": "Alberta",
  "zipCode": "T0K 0K0",
  "country": "Canada"
}

### Delete an existing contact
DELETE http://localhost:3000/contacts/6350d84ce35208eaa16dd647

// USING RENDER
### Display all contacts from Render
GET https://jessewilson341-a2.onrender.com/contacts

### Find a contact by ID from Render
GET https://jessewilson341-a2.onrender.com/contacts/634c3b91ec2716f690e4340b

### Add new contact to address book from Render
POST https://jessewilson341-a2.onrender.com/contacts
Content-Type: application/json

{
  "firstName": "Dominic",
  "lastname": "Caravaggio",
  "streetAddress": "922 Main SW",
  "city": "Cardston",
  "state": "Alberta",
  "zipCode": "T0K 0K0",
  "country": "Canada"
}

### Update an existing contact in address book from Render
PUT https://jessewilson341-a2.onrender.com/contacts/634c3b91ec2716f690e4340b
Content-Type: application/json

{
  "firstName": "Dominic",
  "lastName": "Caravaggio",
  "streetAddress": "123 His Street",
  "city": "Cardston",
  "state": "Alberta",
  "zipCode": "T0K 0K0",
  "country": "Canada"
}

### Delete an existing contact from Render
DELETE https://jessewilson341-a1.onrender.com/contacts/634c3b91ec2716f690e4340b
